#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Enable flakes on the live USB where they're not enabled by default
export NIX_CONFIG="experimental-features = nix-command flakes"

echo "========================================"
echo "  NixOS Homelab Setup"
echo "========================================"
echo ""

# Check we're running as root (required for partitioning/installing)
if [[ $EUID -ne 0 ]]; then
  echo "Error: This script must be run as root."
  echo "  sudo -E bash scripts/setup.sh"
  exit 1
fi

# Detect disk
echo "Available disks:"
lsblk -d -o NAME,SIZE,TYPE | grep disk
echo ""
read -rp "Target disk (e.g., sda or nvme0n1): " DISK_NAME
TARGET_DISK="/dev/${DISK_NAME}"

if [[ ! -b "${TARGET_DISK}" ]]; then
  echo "Error: ${TARGET_DISK} is not a valid block device."
  exit 1
fi

echo ""
echo "WARNING: This will ERASE ALL DATA on ${TARGET_DISK}."
read -rp "Type 'yes' to continue: " CONFIRM
if [[ "${CONFIRM}" != "yes" ]]; then
  echo "Aborted."
  exit 1
fi

# Update disk device in disk.nix if needed
CURRENT_DEVICE=$(grep 'device =' "${REPO_DIR}/hosts/nuc/disk.nix" | head -1 | sed 's/.*"\(.*\)".*/\1/')
if [[ "${TARGET_DISK}" != "${CURRENT_DEVICE}" ]]; then
  echo "Updating disk.nix to use ${TARGET_DISK}..."
  sed -i "s|device = lib.mkDefault \".*\"|device = lib.mkDefault \"${TARGET_DISK}\"|" "${REPO_DIR}/hosts/nuc/disk.nix"
fi

# Partition and format with disko
echo ""
echo "Partitioning ${TARGET_DISK}..."
nix run github:nix-community/disko -- --mode disko "${REPO_DIR}/hosts/nuc/disk.nix"
echo "Disk partitioned and mounted at /mnt."

# Generate hardware config — strip fileSystems/swapDevices (managed by disko)
echo ""
echo "Generating hardware configuration..."
HARDWARE_TMP=$(mktemp)
nixos-generate-config --root /mnt --show-hardware-config > "${HARDWARE_TMP}"

# Keep kernel modules, CPU, platform detection. Remove fileSystems/swapDevices (disko owns those).
# Add bootloader config.
{
  echo "# Generated by setup.sh — fileSystems managed by disko"
  echo "{ config, lib, modulesPath, ... }:"
  echo "{"
  echo "  imports = [ (modulesPath + \"/installer/scan/not-detected.nix\") ];"
  echo ""
  echo "  boot.loader.systemd-boot.enable = true;"
  echo "  boot.loader.efi.canTouchEfiVariables = true;"
  echo ""
  # Extract kernel module lines and platform/CPU lines
  grep -E '^\s+boot\.(initrd\.(availableKernelModules|kernelModules)|kernelModules|extraModulePackages)' "${HARDWARE_TMP}" || true
  echo ""
  grep -E '^\s+nixpkgs\.hostPlatform' "${HARDWARE_TMP}" || true
  grep -E '^\s+hardware\.cpu\.' "${HARDWARE_TMP}" || true
  echo "}"
} > "${REPO_DIR}/hosts/nuc/hardware.nix"

rm -f "${HARDWARE_TMP}"
echo "Hardware config written to hosts/nuc/hardware.nix"
echo ""
echo "--- Generated hardware.nix ---"
cat "${REPO_DIR}/hosts/nuc/hardware.nix"
echo "--- End ---"

# Detect network interface and update config
echo ""
IFACE=$(ip -o link show | grep -v 'lo:' | grep -v 'wl' | head -1 | awk -F': ' '{print $2}')
echo "Detected network interface: ${IFACE}"
CURRENT_IFACE=$(grep 'networking.interfaces\.' "${REPO_DIR}/hosts/nuc/default.nix" | head -1 | sed 's/.*interfaces\.\([a-zA-Z0-9]*\).*/\1/')
if [[ -n "${IFACE}" && "${IFACE}" != "${CURRENT_IFACE}" ]]; then
  echo "Updating default.nix interface from ${CURRENT_IFACE} to ${IFACE}..."
  sed -i "s/networking.interfaces.${CURRENT_IFACE}/networking.interfaces.${IFACE}/" "${REPO_DIR}/hosts/nuc/default.nix"
fi

# Secrets setup
echo ""
echo "========================================"
echo "  Secrets Setup"
echo "========================================"
mkdir -p /mnt/etc/nixos/secrets

# Generate restic backup password
head -c 32 /dev/urandom | base64 > /mnt/etc/nixos/secrets/restic-password
chmod 644 /mnt/etc/nixos/secrets/restic-password
echo "Generated restic backup password."
echo "IMPORTANT: Save this password in your password manager!"
echo "  Password: $(cat /mnt/etc/nixos/secrets/restic-password)"
echo ""

echo "Cloudflare Tunnel credentials."
echo "You need two files from 'cloudflared tunnel create homelab':"
echo "  1. Tunnel credentials JSON (e.g., ~/.cloudflared/<uuid>.json)"
echo "  2. Origin certificate (e.g., ~/.cloudflared/cert.pem)"
echo ""
read -rp "Path to tunnel credentials JSON (leave blank to skip): " CF_CREDS
if [[ -n "${CF_CREDS}" && -f "${CF_CREDS}" ]]; then
  cp "${CF_CREDS}" /mnt/etc/nixos/secrets/cloudflared-tunnel.json
  chmod 644 /mnt/etc/nixos/secrets/cloudflared-tunnel.json
  echo "Credentials saved."
else
  echo "Skipped credentials."
fi

read -rp "Path to origin certificate (e.g., ~/.cloudflared/cert.pem, leave blank to skip): " CF_CERT
if [[ -n "${CF_CERT}" && -f "${CF_CERT}" ]]; then
  cp "${CF_CERT}" /mnt/etc/nixos/secrets/cloudflared-cert.pem
  chmod 644 /mnt/etc/nixos/secrets/cloudflared-cert.pem
  echo "Certificate saved."
else
  echo "Skipped certificate."
fi

# Copy repo to target for the flake reference
echo ""
echo "Copying configuration to /mnt/etc/nixos/homelab..."
mkdir -p /mnt/etc/nixos
rm -rf /mnt/etc/nixos/homelab
cp -r "${REPO_DIR}" /mnt/etc/nixos/homelab

# Install NixOS
echo ""
echo "Installing NixOS (this may take a while)..."
nixos-install --flake "/mnt/etc/nixos/homelab#nuc" --no-root-passwd

echo ""
echo "========================================"
echo "  Installation Complete!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Remove the USB drive"
echo "  2. Reboot: reboot"
echo "  3. SSH in: ssh admin@<nuc-ip> (initial password: changeme)"
echo "     Or use your SSH key if configured in hosts/nuc/default.nix"
echo "  4. Access AdGuard Home at http://<nuc-ip>:3000"
echo "  5. Access Home Assistant at http://<nuc-ip>:8123"
echo "  6. Access Dashboard at http://<nuc-ip>:8082"
echo "  7. Point your router's DNS to the NUC's IP"
echo ""
